packages:
  - 'packages/*'

catalog:
  '@antfu/ni': '^0.23.2'
  'hono': '^4.6.15'
  '@ryoppippi/eslint-config': 'npm:@jsr/ryoppippi__eslint-config'
  'eslint': '^9.17.0'
  'eslint-plugin-format': '^0.1.3'
  'valibot': '^1.0.0-beta.9'
